# ================================
# Configuração do Banco H2
# ================================
spring.datasource.url=jdbc:h2:mem:oficina
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ================================
# Configuração JPA / Hibernate
# ================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================================
# Console H2 (acesse: http://localhost:8080/h2-console)
# ================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ================================
# Porta da aplicação
# ================================
server.port=8080

# ================================
# Spring Boot Actuator
# ================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# ================================
# Prometheus (Micrometer)
# ================================
management.prometheus.metrics.export.enabled=true

# ================================
# SpringDoc / Swagger
# ================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
